### ISSUE TITLE
Is this plugin still being supported?

### ISSUE THREAD

**Issue by ppabon57** [shannonhochkins/webpack-msbuild-plugin#1]
I'm running this plugin with the following:
Windows 10
VS 2017
Webpack4

and currently unable to get this running correctly, I've had an error related to the plugin not having a constructor, is there any work around?

**Comment by shannonhochkins** [comment]
What version of Node are you using mate?


-------- Original Message --------
Subject: [shannonhochkins/webpack-msbuild-plugin] Is this plugin still
being supported? (#1)

**Comment by shannonhochkins** [comment]
Stil no call....


-------- Original Message --------
Subject: [shannonhochkins/webpack-msbuild-plugin] Is this plugin still
being supported? (#1)

**Comment by ppabon57** [comment]
v10.15.1



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by shannonhochkins** [comment]
Can you please create a bug or screen shot the actual issue?Cheers,


-------- Original Message --------
Subject: Re: [shannonhochkins/webpack-msbuild-plugin] Is this plugin
still being supported? (#1)

**Comment by ppabon57** [comment]
![image](https://user-images.githubusercontent.com/25090251/53758915-18450c80-3e8d-11e9-9c7c-a549f0d1d8e5.png)

**Comment by shannonhochkins** [comment]
Whats your webpack config look like? Seems like your config file or import is wrong as it's not my plugin that's throwing the error it's your setup itself through webpack cli.Make sure you add the require block or import your node module after you install it.const WebpackMSBuildPlugin = require('webpack-msbuild-plugin');Cheers,


-------- Original Message --------
Subject: Re: [shannonhochkins/webpack-msbuild-plugin] Is this plugin
still being supported? (#1)

**Comment by ppabon57** [comment]
I have a base config which I import....but may main dev config where I've added your plugin was something like this.....


/***************************
* Imports
****************************/
const commonConfig = require('./webpack.common.js');
const merge = require('webpack-merge');
const webpack = require('webpack');
const WebpackMSBuildPlugin = require('webpack-msbuild-plugin');

/***************************
* Exports
****************************/
module.exports = function (env, argv) {

    console.log('Running development build...');

    const devConfig = {
        mode: 'development',
        plugins: [
            new webpack.DefinePlugin({
                ENV_IS_DEVELOPMENT: true
            }),
            new webpack.NamedModulesPlugin(),
			new WebpackMSBuildPlugin({
				onWebpackDone: {                        
					projects: ['src/project/website/code/myproject.csproj']
				}
			})
        ]
    };

    return merge(commonConfig(env, argv), devConfig);

};

**Comment by shannonhochkins** [comment]
Zip up your setup and send it over mate


-------- Original Message --------
Subject: Re: [shannonhochkins/webpack-msbuild-plugin] Is this plugin
still being supported? (#1)

**Comment by gitrifatjahanazad** [comment]
I am also facing this issue till today.
